# Copyright 2023 Linus Arver
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#+title: melby images
#+PROPERTY: header-args :noweb no-export
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="syntax-highlighting.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />

* Architecture

The SVG file we generate here is not deterministic (changes every time we
generate it).

It appears that it generates the wrong thing as SVG (the SVG itself is valid but
the shapes displayed are parts of the text strings used for generating the SVG).

Note that this pdf generation works fine. However if we specify SVG it doesn't
work.

We can now convert the minimal 1-page PDF into an SVG using either [[https://github.com/mgieseki/dvisvgm][dvisvgm]] or
[[https://github.com/dawbarton/pdf2svg][pdf2svg]]. Currently (September 2022) there is [[https://github.com/mgieseki/dvisvgm/issues/183][a bug]] with dvisvgm so we have to
use the latter. Ideally Org mode can take care of this but currently it appears
to be buggy, so we perform the manual conversion ourselves. We might even want
to create a separate Org mode doc for all of the svg image processing. FIXME

FIXME: Also, we need to basically do 2 passes --- run emacs to generate the HTML
and all PDF (images) files, and a second pass with pdf2svg to generate the svgs.

#+name: architecture-overall
#+caption: Generates =image/architecture-overall.pdf=.
#+header: :eval yes
#+header: :results file drawer
#+header: :file image/architecture-overall.pdf
#+header: :imagemagick yes
#+header: :headers '("\\usepackage{tikz}" "\\usepackage[default]{sourcesanspro}")
#+begin_src latex
% See https://tex.stackexchange.com/a/445446 which was used as a template for
% this diagram below.
\usetikzlibrary{
  arrows.meta,
  calc,
  shapes.geometric,
  shapes.symbols,
  fit,
  positioning}
\tikzset{
  module/.style={%
    fill=white,
    draw=black, rounded corners,
    % Minimum height is useful to take into account capital
    % letters and such that take up extra height.
    minimum height=7mm,
    align=center,
    font=\sffamily
  },
  user/.style={%
    shape=ellipse,
    fill=white,
    draw=black, rounded corners,
    % Minimum height is useful to take into account capital
    % letters and such that take up extra height.
    minimum height=7mm,
    align=center,
    font=\sffamily
  },
  arrowX/.style={%
    {Latex[length=2mm,width=2mm]}-{Latex[length=2mm,width=2mm]}
  },
  arrowL/.style={%
    {Latex[length=2mm,width=2mm]}-
  },
  arrowR/.style={%
    -{Latex[length=2mm,width=2mm]}
  }%
}
\begin{tikzpicture}[thick,font=\sffamily,every label/.append
    style={font=\sffamily,align=center}]

% Lua VMs. This is the "root" node as it does not reference anything
% else in terms of positioning.
\node[module, label={[yshift=3mm]Daemon\\(melbyd)}] (LuaVMs) {Lua VMs};
% Outer box around melbyd, which includes the LuaVMs.
\node[fit={(0,2) (LuaVMs) (0,-1)}, draw, rounded corners,
  inner xsep=5mm, inner ysep=-\pgflinewidth] (melbydOutline) {};
\node[module, left=1.5cm of melbydOutline] (melbyr) {Renderer\\(melbyr)};

% We could just use "right=1.5cm of melbydOutline" here but use calc's syntax
% for computing a coordinate combined with a (X,Y) delta for future reference in
% case we need to fine-tune an illustration.
\node[module] at ($(melbydOutline) + (3.5cm,0cm)$) (melbyc) {Client\\(melbyc)};
\node[module, right=1cm of melbyc] (Configs) {Configs\\(Lua)};
\node[user, below=1.5cm of melbyc] (User) {User};

\draw[arrowX] (melbyr)--(melbydOutline);
\draw[arrowX] (User)--(melbyc);
\draw[arrowL] (melbyc)--(Configs);
\draw[arrowX] (melbyc)--(melbydOutline);

\end{tikzpicture}
#+end_src

* Makefile

This is a Makefile for generating diagrams (SVG format).

#+name: image/Makefile
#+caption: =image/Makefile=
#+begin_src makefile :tangle image/Makefile :eval no
all: architecture-overall.svg
%.svg : %.pdf
	pdf2svg $< $@.uncropped.svg
	inkscape \
		--export-plain-svg \
		--export-margin=5 \
		--export-filename=$@ \
		--export-area-drawing \
		$@.uncropped.svg

.PHONY: all
#+end_src
