# Copyright 2023 Linus Arver
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#+title: Melby

#+SETUPFILE: lilac.theme

# Set default header argument for all source code blocks. The "no-export" means
# that we do not expand noweb references when exporting (weaving) --- the fact
# that this is not the default option is odd.
#+PROPERTY: header-args :noweb no-export

# Prevent _ and ^ from being interpreted as subscript and superscript operators.
#+OPTIONS: ^:{}

# Number the top 5 levels of headings; since h1 is the tile, this means headings
# up to 4 numbers --- e.g., "1.2.3.4".
#+OPTIONS: H:5

# Note that this is a comment and is not woven (exported) to HTML, nor visible
# from any tangled (generate) source code file. Below is a block comment:
#+begin_comment
This is a sample multi-line comment.
Also see https://orgmode.org/manual/Comment-Lines.html.
#+end_comment

* Introduction

NOTE: THIS PROJECT IS NOT EVEN BETA. EXPECT REGULAR BREAKAGES.

#+begin_sidenote
The name /melby/ comes from /Melbourne/, the capital city of the state of
Victoria, Australia.
#+end_sidenote

Melby is a configurable *shell prompt generation system*. Typically, users
customize their shell prompt by making it run a collection of useful shell
commands, such as =git= for Git status information, and piecing this output
together into the =PS1= shell variable found in most shells. This is problematic
when those commands can take a long time (more than a few seconds) to run,
because it introduces a delay between each shell prompt generation. Nobody likes
to wait a few seconds for the shell prompt to finish rendering.

Users are then forced to strip down the commands used for the shell prompt to
only those commands that run very quickly. Melby was written to generate a shell
prompt string in under 1 second, even if the commands used for gathering
information to be used by the shell prompt take much longer. Melby achieves this
by running things asynchronously and caching results.

** How the rest of the documentation is organized

There are two manuals in this project:

1. [[file:developer-manual.html][Developer Manual]]
2. [[file:user-manual.html][User Manual]]

The [[file:developer-manual.html][*Developer Manual*]] is written to help other programmers understand how
everything works, while the [[file:user-manual.html][*User Manual*]] is written for end-users.
