// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ViewRequest {
    /// Path to Lua configuration. Delegates reading the config to the server.
    #[prost(string, tag = "1")]
    pub config_path: ::prost::alloc::string::String,
    /// Lua configuration that is given directly. Overrides config_path if not
    /// empty.
    #[prost(string, tag = "2")]
    pub config: ::prost::alloc::string::String,
    /// Environment variables ((name, value) pairs) of interest.
    #[prost(map = "string, string", tag = "3")]
    pub env_vars: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Process ID number of the running (interactive) shell program. (FIXME: move
    /// this to env var)
    #[prost(string, tag = "4")]
    pub shell_pid: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ViewResponse {
    /// Status of this response message.
    #[prost(enumeration = "ViewStatus", tag = "1")]
    pub status: i32,
    /// String result of running Lua script.
    #[prost(string, tag = "2")]
    pub view: ::prost::alloc::string::String,
    /// Error message from melbyd, if any.
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ViewStatus {
    Unspecified = 0,
    Error = 1,
    Ok = 2,
}
impl ViewStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ViewStatus::Unspecified => "VIEW_STATUS_UNSPECIFIED",
            ViewStatus::Error => "VIEW_STATUS_ERROR",
            ViewStatus::Ok => "VIEW_STATUS_OK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VIEW_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "VIEW_STATUS_ERROR" => Some(Self::Error),
            "VIEW_STATUS_OK" => Some(Self::Ok),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod view_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// melbyc <-> melbyd communication
    #[derive(Debug, Clone)]
    pub struct ViewClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ViewClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ViewClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ViewClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            ViewClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_view(
            &mut self,
            request: impl tonic::IntoRequest<super::ViewRequest>,
        ) -> std::result::Result<tonic::Response<super::ViewResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/melby_client.View/GetView",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("melby_client.View", "GetView"));
            self.inner.unary(req, path, codec).await
        }
    }
}
