#!/usr/bin/env bash
set -euo pipefail

SCRIPT_ROOT="$(dirname "$(realpath "$0")")"

cd "${SCRIPT_ROOT}"

# Daemonize with the "-d" flag.
if [[ "${1:-}" == -d ]]; then
    nix-shell --command "nohup elixir --sname melbyd \
        --erl '-kernel inet_dist_listen_min 33001 inet_dist_listen_max 33001' \
        -S mix run --no-halt >/dev/null & disown"
else
    nix-shell --command "elixir --sname melbyd \
        --erl '-kernel inet_dist_listen_min 33001 inet_dist_listen_max 33001' \
        -S mix run --no-halt"
fi
